#include "nrf_gpio.h"
#include "nrf_saadc.h"

//define flex sensor readout pins
#define SENSOR_0_INPUT_PIN NRF_SAADC_INPUT_AIN3 //0.05
#define SENSOR_1_INPUT_PIN NRF_SAADC_INPUT_AIN4 //0.28
#define SENSOR_2_INPUT_PIN NRF_SAADC_INPUT_AIN5 //0.29
#define SENSOR_3_INPUT_PIN NRF_SAADC_INPUT_AIN6 //0.30
#define SENSOR_4_INPUT_PIN NRF_SAADC_INPUT_AIN7 //0.31

uint8_t PWM_OUTPUT_PIN = NRF_GPIO_PIN_MAP(0, 17);
