#include "nrf_gpio.h"
#include "nrf_saadc.h"

//define flex sensor readout pins
#define SENSOR_0_INPUT_PIN NRF_SAADC_INPUT_AIN0 //0.02
#define SENSOR_1_INPUT_PIN NRF_SAADC_INPUT_AIN1 //0.03
#define SENSOR_2_INPUT_PIN NRF_SAADC_INPUT_AIN2 //0.04
#define SENSOR_3_INPUT_PIN NRF_SAADC_INPUT_AIN3 //0.05
#define SENSOR_4_INPUT_PIN NRF_SAADC_INPUT_AIN4 //0.28

uint8_t PWM_OUTPUT_PIN = NRF_GPIO_PIN_MAP(0, 17);
